# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8c7ea2ea40b5f6bd481160ca9b4bc2d543f9f40dd1f19564d6fb0e3a668b2488e6aaa33843eec1a51c922f40e486651693bfe2b4201bb58508401a2d4fe5ed5c

test:
  secret_key_base: a354d7566f9951c965360c8530b1c4d047e57eaf32fc4a6ff34b530591deb2b17ba849878e6afd691cd99398f7d79259f32366912f4aad4d0cc7b526ab63d3fe

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
